target_url: "https://testphp.vulnweb.com"

scan_types:
  - sast
  - dast
  - dependency
  - nuclei
  - nmap

report:
  format: ["json","html"]

session:
  check_jwt: true

nuclei:
  templates: null  # optional: path to custom templates or comma-separated templates

nmap:
  fast: true
