target_url: "https://example.com"
scan_types:
  - dast
  - sast
  - dependency
auth:
  username: "tester"
  password: "password123"
session:
  check_jwt: true
  check_cookie_flags: true
report:
  format: ["html", "json"]
ci_cd:
  notify_slack: true
  fail_on_high_severity: true
