name: OWASP Framework Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run OWASP Framework
      run: |
        source venv/bin/activate
        python3 main.py

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: scan-reports
        path: reports/
